### PR TITLE
Edit Fix path generation in windows (followup #187)

### PR DESCRIPTION
**Pull request by filipesilva**
Followup from #187 

I reapplied the code you had in the `nodefix` branch, but I'm still running into some trouble due to some new code.

In line 1299, this condition is never met and thus `ender()` is never called:

```
                            total += tot;
                            if (total[1] === total[0]) {
                                ender();
                            }
```

The `total` variable is, before and after assignment
```
[ 1, 0 ]
1,01
```

Which makes me thing there's a problem in that assignment (due to it being coerced from an array to a string.

EDIT: I also had to comment out line 2322 `help =  true` otherwise I couldn't even read the rc file.

### CODE REVIEW

**Comment by prettydiff** [comment]
Yeah, that is absolutely a defect.  I will look into these items this morning.

**Comment by prettydiff** [comment]
The assignment to pdrcpath is causing me problems:

    pdrcpath  = (process.cwd() === "/")
        ? path.join(__dirname.replace(/((\/|\\)api)$/, ""), "/.prettydiffrc")
        : path.join(process.cwd().replace(/((\/|\\)api)$/, ""), ".prettydiffrc")

If I am running this locally in the exact directory of the `node-local.js` file everything works correctly, but if I am in a different directory and running it locally the `.prettydiffrc` file cannot be resolved.  Here is an example:

If CLI is at `c:\temp` and node file is at `c:\temp\node_modules\prettydiff\api\node-local.js` the command `node node_modules\prettydiff\api\node-local.js` looks for the rc file at `c:\temp\.prettydiffrc`.  I get pretty much the same thing when I run this globally.

I will be considering options on how to determine the best relative/absolute path for this today for these scenarios:

* Running locally from a relative location
* Running locally from an absolute location
* Running from global install

**Comment by filipesilva** [comment]
I might have misunderstood the purpose of that file resolution, but the behavior you describe is what I would expect from a CLI tool. My use case is as follows:

I start a angular project at `c:\temp\proj`. I add a `.gitignore` excluding `node_modules` and `bower_components`, and initialize `package.json` with the set of packages I intend to use: bower, webpack, eslint, prettydiff, karma and protractor (these last two for tests). These tools allow configuration via files, and upon running them locally or globally, they will read these config files and act upon my projects files. 

Running `node c:\temp\proj\node_modules\prettydiff\api\node-local.js` I am expecting it to look for the configuration file in `c:\temp\proj\.prettydiffrc`, since that is the file I keep in version control. If it were to be resolved to `c:\temp\proj\node_modules\prettydiff\api\.prettydiffrc` then I could not keep the file in version control since I have git ignoring `node_modules`.

Can you describe to me the use case you are aiming for? I suspect it is not the same as mine.

**Comment by prettydiff** [comment]
What about this:

    pdrcpath  = (process.cwd() === "/" || process.cwd() === "c:\\")
                    ? __dirname.replace(/(api)$/, "") + ".prettydiffrc"
                    : "../.prettydiffrc",

This seems to work in all cases for me.

**Comment by prettydiff** [comment]
I went ahead and merged this because I am trying to get a bunch of stuff published, I might get laid off from my primary job next week, and I will going out of town next week for a military school.  I thought since this file broken anyways the current solution might as well go out.

If the current code is still failing I would love to continue to work with you on this.

**Comment by filipesilva** [comment]
Hey man, i haven't been around either so haven't looked at this again. I hope you managed to keep your job :/

**Comment by prettydiff** [comment]
We were supposed to find out last week, but they pushed the decision out to Thursday of this week.  Everybody company-wide finds out their status at the same time.

**Comment by filipesilva** [comment]
That sucks man. The wait :/

**Pull request merged**
