### PR TITLE
Fix Liquid comment & 'for' iteration tags glitch

### PR DESCRIPTION
**Pull request by hdytsgt**
Hey!

I found an issue with Liquid comment having glitch when running Beautify and/or Minify. This is code source to be beautified/minified
`{% comment %}
    This should be fail
{% endcomment %}
<div class="sample">
    Sample Content
</div>`

When running Beautify/Minify it throws an error : 
issue

This PR fix the issue, please review.

### CODE REVIEW

**Comment by prettydiff** [comment]
If your pull request is correct this is a simple solution is a catastrophic problem.  I may not have time to fully review this today, but I plan to either recommend changes or merge before Monday.

**Comment by hdytsgt** [comment]
Sounds good!

**Comment by hdytsgt** [comment]
Additional [fix](https://github.com/prettydiff/prettydiff/pull/364/commits/9e77154ab5f2dfc2cc4b026262643071f6d36b96) to this PR. 

Currently [twigfix](https://github.com/prettydiff/prettydiff/blob/master/lib/markuppretty.js#L2718) only works for this format :
```
{% for i in 1..8 %}
    {{ i }}
{% endfor %}
```
But this will fail : 
```
{% for i in(1..8) %}
    {{ i }}
{% endfor %}
```
```
{% for i in (1..8) %}
    {{ i }}
{% endfor %}
```
This fix will works on all of them.

**Comment by prettydiff** [comment]
I reviewed the pull request.  It doesn't look like the various parsing arrays are being populated in an unequal way.  You can verify this by adding something like `console.log(token.length+" "+types.length+" "+attrs.length+" "+jscom.length)`.  If everything is the same length then they are populated in parallel.  This doesn't necessarily mean the parsing is correct, but it does mean everything is uniformly parallel.

It seems this particular issue is related more to sloppy beautification than a parsing problem.  There is another language called [Twig](http://twig.sensiolabs.org/) that looks similar and the beautifier is making a faulty assumption.

When I changed this line:

    if (twigStart.test(token[a]) === true && twigEnd.test(token[a]) === true && (/\D-+\D/).test(token[a]) === false && (/^(\{%\s*((comment)|(else))\s*)/).test(token[a]) === false) {

To this:

    if (twigStart.test(token[a]) === true && twigEnd.test(token[a]) === true && tagName(token[a - 1]) !== "script" && tagName(token[a - 1]) !== "style" && (/\D-+\D/).test(token[a]) === false && (/^(\{%\s*((comment)|(else))\s*)/).test(token[a]) === false) {

It seems to solve the problem where the difference is that I stopped presuming Twig logic if its inside a script or type tag.

**Comment by prettydiff** [comment]
I just reviewed your second change for the `for in` loops and it is spot on.  Once you apply the suggested fix for the original defect I will merge this in.

**Comment by prettydiff** [comment]
Merged into branch 2.1.11.

**Pull request closed without merging**
