### PR TITLE
Fix path generation in windows

### LINKED ISSUE #185: CLI not recognizing .prettydiffrc
Running CLI commands with arguments seems to work, but the `.prettydiffrc` file doesn't seem to be recognized (help message is always displayed). 

This might be related with me being on windows, via gitbash (which uses mingw).

image

### PR DESCRIPTION
**Pull request by filipesilva**
Close #185

### CODE REVIEW

**Comment by prettydiff** [comment]
I think we have gotten out sync and trying to update the code in the master branch only resulted in a merge conflict.  I have created a new branch `nodefix` to work out of.

I noticed between the two versions there were quite a few changes in the directory `writing`.  These were mostly due to a last minute update on my side, because I noticed in Windows the summary information were printing to console well before the files had finished writing.  Perhaps the most major difference is this line `pdrcpath  = __dirname.replace(/((\/|\\)api)$/, "") + "/.prettydiffrc"`, because I found it is more stable if the `.prettydiffrc` file is always resolved relative to where the node file executes opposed to what the current directory is.

**Comment by filipesilva** [comment]
Apologies, I've been travelling this past week on holidays and haven't had time to sit down and check this out. I'll do so in the next few days.

**Comment by filipesilva** [comment]
Regarding `pdrcpath = __dirname.replace(/((\/|\\)api)$/, "") + "/.prettydiffrc"`, if the path is always resolved relative to the node file, then it never would find `.prettydiffrc` files outside of the prettydiff node module folder. 

Or am I missing something? For instance, right now this is the path I get if I put that path resolution in place

```
E:\sandbox\prettydiffrctest\node_modules\prettydiff\.prettydiffrc
```

Whereas the correct one would be

```
E:\sandbox\prettydiffrctest\.prettydiffrc
```

**Comment by filipesilva** [comment]
(continued in #195)

**Comment by prettydiff** [comment]
Newer pull request at #195

**Pull request closed without merging**
