### PR TITLE
Fixed #141 and #143

### LINKED ISSUE #141: Nested rules not indented in SCSS
Nested rules aren't indented in SCSS if the option to insert new lines between rules is checked.
This only effects the nested rules that aren't the first on that level.

Original:
```scss
header .navbar-nav {
  float: none;
}
footer {
  .navbar {
    min-height: 25px;
  }
  .other-class {
    min-height: 25px;
  }
  .other-class-2 {
    min-height: 25px;
  }
}
```

Expected:
```scss
header .navbar-nav {
  float: none;
}

footer {
  .navbar {
    min-height: 25px;
  }

  .other-class {
    min-height: 25px;
  }
  
  .other-class-2 {
    min-height: 25px;
  }
}
```

Actual:
```scss
header .navbar-nav {
  float: none;
}

footer {
  .navbar {
    min-height: 25px;
  }
  
.other-class {
    min-height: 25px;
  }
  
.other-class-2 {
    min-height: 25px;
  }
}
```

### PR DESCRIPTION
**Pull request by ArekSredzki**
Changed how new lines are inserted for SCSS, if the option is on.

### CODE REVIEW

**Comment by ArekSredzki** [comment]
Ready to pull, but the dist has to be compiled.

**Comment by prettydiff** [comment]
I was unable to reproduce the problem and when I ran the sample code through.  What kind of symptoms did you identify that I didn't notice?  I am reviewing the pull request now.

**Comment by ArekSredzki** [comment]
@prettydiff Please let me know if my changes fixed the issue once you've gotten a chance to test them.  I wasn't able to as your dev env isn't clearly documented in the repo (at least I didn't see it).
Thanks!

**Comment by prettydiff** [comment]
Couple of things.

1. You are right about the lack of documentation about my development environment and I need to address this.  On my local I just work directly in the big prettydiff.js file.  I don't have any build process.  The smaller libs are provided separately for convenience and exist directly within the big prettydiff.js file.
2. Your assessment of the problem cause is 100% correct.  The approach you suggested was close but did not work for me.

What did work for me is the change this:

    if (scssinsertlines === true && types[a + 1] !== "end") {
        build.push("\n");
     }

to

    if (scssinsertlines === true && types[a + 1] !== "end") {
        build.splice(build.length - indent, 0, "\n");
     }

This is the code that you suggested removing at the bottom of the `types[a] === "end"` condition.  The extra new line just needed to be inserted before any indentation instead of after indentation.  If you wouldn't mind altering your pull request I will gladly merge this in.

**Comment by ArekSredzki** [comment]
It turned out that I thought that `"start"` was what `"selector"` actually is.
I've made the correct changes, and tested it properly.
New lines now work for selectors too.

I'd love to see this change in use :)

**Comment by ArekSredzki** [comment]
:')

**Comment by ArekSredzki** [comment]
@prettydiff Just wondering, why'd you end up moving back to postfixing the spacing rather than prefixing? it was much simpler the way that I had it.

**Comment by prettydiff** [comment]
I found some conflicts.  I remembered that your fix and the other several attempts I tried encountered some collisions.  Your attempt was the most simple and almost the most perfect.  I will see if I can reproduce some of what I saw.  This issue was more challenging after accounting for the 2 CSS options: sorting and forcing an empty line above selectors.  Some of what I remember seeing is that in some cases there would be 2 empty lines inserted above sorted selectors instead of one and only in certain cases.

I am still glad for your examination on this.  Your changes to the code really helped point me in the right direction and gave me additional things to look for.

**Pull request merged**
